Algoritmo "Exercicio 40"

Var
   n1,n2,n3,NF:real


Inicio
      Escreva("nota 1: ")
      Leia(n1)
      Escreva("nota 2: ")
      Leia(n2)
      Escreva("nota 3: ")
      Leia(n3)
      
      NF<-(n1+n2+n3)/3
      Escreval("-----------------------")
      SE NF>=7 entao
      Escreva("Parabens! Passou de Ano!")
      senao
           Escreva("Se fudeu")
      fimse


Fimalgoritmo